service: fixall-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  getWorkers:
    handler: lib/functions/workers/getWorkers.handler
    events:
      - http:
          path: workers
          method: get